default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: save_star_trek_fan_films

test:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: save_star_trek_fan_films_test

production:
  # To be populated by Heroku