development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  database: save_star_trek_fan_films
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  database: save_star_trek_fan_films_test
  pool: 5
  timeout: 5000

production:
  # To be populated by Heroku